# Assetic Configuration

assetic:
    debug: %kernel.debug%
    use_controller: true
    bundles: [ ]
#    java: %java_path%
    filters:
        cssrewrite: ~
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
        lessphp: ~
    assets:
        lesses:
            inputs:
#                - %kernel.root_dir%/../web/assets/bootstrap-2.3.2/less/bootstrap.less
#                - @BricksSiteBundle/Resources/less/*.less

            filters: lessphp

        stylesheets:
            inputs:
                #-- Font Awesome CSS --#
                - %kernel.root_dir%/../web/assets/css/font-awesome.min.css
                #-- Bootstrap CSS --#
                - %kernel.root_dir%/../web/assets/css/bootstrap.min.css
                #-- App CSS --#>
                - %kernel.root_dir%/../web/assets/css/mvpready-admin.css
                - %kernel.root_dir%/../web/assets/css/mvpready-flat.css

#                - %kernel.root_dir%/../web/assets/css/datepicker/bootstrap-datepicker.min.css


                - bundles/rbsoftabmgenerador/fileupload//css/fileinput.min.css
#                - bundles/app/js/admin/plugins/bootstrap-datepicker/datepicker3.css



#                - %kernel.root_dir%/../web/assets/css/extensions/bootstrap-image-gallery.css
                #- %kernel.root_dir%/../web/assets/css/main.css

                - @lesses
#                - %kernel.root_dir%/../web/assets/FortAwesome-Font-Awesome-3.0/css/font-awesome.min.css
            filters:
                - cssrewrite
                - ?yui_css
        javascripts_header:
            inputs:
#                - %kernel.root_dir%/../web/assets/js/jquery-ui.js
                - bundles/fosjsrouting/js/router.js
#                - bundles/app/js/frontend/ajaxTool.js
#                - bundles/rbsoftabmgenerador/fileupload//js/fileinput.js
            filters:
                - cssrewrite
                - ?yui_js
        javascripts_footer:
            inputs:

#                - bundles/app/js/admin/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.es.js
#                - bundles/app/js/admin/mvpready-core.js
#                - bundles/app/js/admin/mvpready-admin.js

            filters:
                - cssrewrite
                - ?yui_js
