rb_soft_reporte:
    resource: "@RBSoftReporteBundle/Controller/"
    type:     annotation
    prefix:   /

_user_admin:
    resource: "@UserAdminBundle/Controller/"
    type:     annotation
    prefix:   /

_user:
    resource: "@UsuarioBundle/Controller/"
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: @AppBundle/Controller/
    type:     annotation
