services:
    uta.trabajadormodel:
        class: AppBundle\Model\TrabajadorModel
        arguments: [@doctrine.orm.entity_manager , @uta.empleador_activo]

    uta.empleadormodel:
        class: AppBundle\Model\EmpleadorModel
        arguments: [@service_container]

    uta.empleador_activo:
        class: AppBundle\Servicios\EmpleadorActivo
        arguments: [@security.context , @doctrine.orm.entity_manager]

    uta.liquidacion:
        class: AppBundle\Servicios\LiquidacionManager
        arguments: [@service_container]

    twig.extension.uta.empleador:
        class:  AppBundle\Twig\Extension\UtaExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension}

    uta.after_login:
        class: AppBundle\Servicios\LoginRedirect
        arguments: [@router]
#        tags:
#            - { name: kernel.event_subscriber }
