services:
    uta.trabajadormodel:
        class: AppBundle\Model\TrabajadorModel
        arguments: [@doctrine.orm.entity_manager , @uta.empleador_activo]

    uta.empleadormodel:
        class: AppBundle\Model\EmpleadorModel
        arguments: [@service_container]

    uta.empleador_activo:
        class: AppBundle\Servicios\EmpleadorActivo
        arguments: [@security.context , @doctrine.orm.entity_manager]

    uta.liquidacion:
        class: AppBundle\Servicios\LiquidacionManager
        arguments: [@service_container]