<?php

namespace AppBundle\Entity;

/**
 * CtacteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CtacteRepository extends \Doctrine\ORM\EntityRepository
{
}
