<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PeriodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodoRepository extends EntityRepository
{
    /**
     * getMaxNumeroLiq
     * Obtiene la liquidacion maxima para un periodo determinado
     * @param Empleador $emp
     * @param $periodo
     * @return int/mixed
     */
    public function getLiquidaciones(Empleador $emp, $periodo)
    {
//        $liqarray = array();
        $q = $this->_em->createQuery(
            "
            Select p.liquidacion, max(p.tipo) as tipo
            From AppBundle:Periodo p
            where p.empleador = :empleador AND p.vencimiento = :periodo
            GROUP BY p.liquidacion
            order BY p.liquidacion DESC, p.tipo DESC
             "
        )
            ->setParameter("empleador", $emp->getId())
            ->setParameter("periodo", $periodo);

        $liqarray = $q->getArrayResult();

        //saco un numero mas de liquidacion
        $liqmas = ($liqarray [0]['liquidacion'] )+ 1;


        $liqarray[] = array('liquidacion' => $liqmas , 'tipo' => 0);

        return $liqarray;
    }


}
